Token validation
Quickzand/StoryForge pull request #22
Opened 2024-02-04 06:33 UTC by maximusmith529

## Overall Description:

Added functionality token validation of existing tokens.

## What Was Changed:

Added token validation procedure to create_storyforge_db.sql and an api endpoint in server.js

## Any Notes For Testing:

**THIS HAS NOT BEEN TESTED**

## Link To Ticket:

[Link to the ticket this pr is for](https://trello.com/c/Pw7FkBGo/36-token-validation)

2024-02-04 19:56 UTC, sethlenhof commented
I tested and it works, I would prefer we name the endpoint "/api/validateToken" to follow the naming conventions of other endpoints.

2024-02-05 04:36 UTC, sethlenhof requested changes
Tested and it works. Change the endpoint to be "api/tokenValidation" to be more in line with out current endpoints.

2024-02-11 17:32 UTC, sethlenhof approved these changes

2024-04-02 19:12 UTC, maximusmith529 reviewed
lgtm

2024-04-02 19:12 UTC, merged